# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: /Users/dreds/Documents/projects/template-gallery-spike/templates/typescript-smart-contract
author_email: ''
author_name: ''
contract_name: hello_world
preset_name: starter
project_name: Hello World TypeScript Smart Contract

