# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: /Users/dreds/Documents/projects/template-gallery-spike/templates/base-templates/typescript-smart-contract
author_email: john@example.com
author_name: Alyosha
contract_name: hello_world
preset_name: starter
project_name: Hello World TypeScript Smart Contract

