name: Create Example Branches

on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'

jobs:
  create-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Create branches for examples
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git to use the token for authentication
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          
          # Get list of example directories
          for dir in examples/*/; do
            # Remove trailing slash and examples/ prefix from directory name
            dir_name=${dir#examples/}
            dir_name=${dir_name%/}
            
            # Create branch name
            branch_name="examples/$dir_name"
            
            echo "Processing $dir_name..."
            
            # Check if branch exists
            if git show-ref --quiet refs/remotes/origin/$branch_name; then
              # Branch exists, update it
              git checkout -b $branch_name origin/$branch_name
            else
              # Create new branch
              git checkout -b $branch_name
            fi
            ls -la
            
            # First, move the target directory to temp to preserve it
            mkdir -p temp
            # mv examples/$dir_name/* temp/    
            mv examples/$dir_name/.[!.]* examples/$dir_name/* temp/ 2>/dev/null || true        
            ls -la temp
            # Remove everything except .git and temp directories
            find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name 'temp' -exec rm -rf {} +            
            # Move the preserved content back including hidden files
            mv temp/.[!.]* temp/* ./ 2>/dev/null || true
            rm -rf temp
            ls -la
            
            # Add and commit changes
            git add .
            git commit -m "Update example branch $branch_name"
            
            # Push branch
            git push -f origin $branch_name
            
            # Return to main branch for next iteration
            git checkout main
            git clean -fd
            git reset --hard origin/main
          done 