name: Publish Demo Sites

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # You can specify any version you need

      - name: Parse examples and build frontends        
        run: |
          # # Debug PATH and npm location
          # echo "PATH=$PATH"
          # which node
          # which npm
          
          # Create a directory for all builds
          mkdir -p dist
          
          # Get repository name for base path
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          
          # Read examples.yml and filter frontend examples
          FRONTEND_EXAMPLES=$(yq e '.examples | map(select(.type == "frontend"))' examples/examples.yml)
          
          # Process each frontend example as a complete object
          echo "$FRONTEND_EXAMPLES" | yq e -o=json -I=0 '.' - | jq -r '.[] | @json' | while read -r example; do
            ID=$(echo "$example" | jq -r '.id')
            REPO_PATH=examples/$ID
            
            echo "Building frontend example: $ID with path $REPO_PATH"
            
            # Navigate to example directory and build
            cd "$REPO_PATH" || exit 1
            
            # Add BASE_PATH environment variable for the build
            export BASE_PATH="/${REPO_NAME}/${ID}"
            npm ci
            npm run build
            
            # Move build output to dist directory
            mkdir -p "../../dist/$ID"
            mv dist/* "../../dist/$ID/"
            
            # Return to root
            cd ../../
          done

          # Copy the index.html from examples to dist
          cp examples/index.html dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
