name: Publish Demo Sites

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # You can specify any version you need

      - name: Verify Node.js and npm installation
        run: |
          echo "Node.js version:"
          node --version
          echo "npm version:"
          which npm
          npm --version

      - name: Parse examples and build frontends
        run: |
          # # Debug PATH and npm location
          # echo "PATH=$PATH"
          # which node
          # which npm
          
          # Create a directory for all builds
          mkdir -p dist
          # Echo current directory and contents
          echo "Current directory:"
          pwd
          
          # Read examples.yml and filter frontend examples
          FRONTEND_EXAMPLES=$(yq e '.examples[] | select(.type == "frontend")' examples/examples.yml)
          
          # Process each frontend example as a complete object
          echo "$FRONTEND_EXAMPLES" | yq e -o=json -I=0 '.' - | jq -c '.' | while read -r example; do
            ID=$(echo "$example" | jq -r '.id')
            REPO_PATH=examples/$ID
            
            echo "Building frontend example: $ID with path $REPO_PATH"
            
            # Navigate to example directory and build
            cd "$REPO_PATH" || exit 1
            npm ci
            npm run build
            
            # Move build output to dist directory
            mkdir -p "../../dist/$ID"
            mv dist/* "../../dist/$ID/"
            
            # Return to root
            cd ../../
          done
      # Create a top-level index.html with links to all demos
      cat > dist/index.html << 'EOL'
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Template Gallery Demo Sites</title>
          <style>
              body {
                  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
                  max-width: 800px;
                  margin: 2rem auto;
                  padding: 0 1rem;
              }
              h1 { color: #333; }
              ul { list-style-type: none; padding: 0; }
              li { margin: 1rem 0; }
              a {
                  color: #0066cc;
                  text-decoration: none;
              }
              a:hover { text-decoration: underline; }
          </style>
      </head>
      <body>
          <h1>Template Gallery Demo Sites</h1>
          <ul>
              <li><a href="frontend-example-1-astro/">Frontend Example 1 - Astro</a></li>
              <li><a href="frontend-example-1-react/">Frontend Example 1 - React</a></li>
          </ul>
      </body>
      </html>
      EOL

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
