name: Publish Demo Sites

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # You can specify any version you need

      - name: Verify Node.js and npm installation
        run: |
          echo "Node.js version:"
          node --version
          echo "npm version:"
          which npm
          npm --version

      - name: Parse examples and build frontends
        shell: bash
        run: |
          # # Debug PATH and npm location
          # echo "PATH=$PATH"
          # which node
          # which npm
          
          # Create a directory for all builds
          mkdir -p dist
          # Echo current directory and contents
          echo "Current directory:"
          pwd
          
          # Read examples.yml and filter frontend examples
          FRONTEND_EXAMPLES=$(yq e '.examples[] | select(.type == "frontend")' examples/examples.yml)
          
          # Process each frontend example as a complete object
          echo "$FRONTEND_EXAMPLES" | yq e -o=json -I=0 '.' - | jq -c '.' | while read -r example; do
            ID=$(echo "$example" | jq -r '.id')
            PATH=examples/$ID
            
            echo "Building frontend example: $ID with path $PATH"
            
            # Navigate to example directory and build
            cd "$PATH" || exit 1
            echo "Current directory:"
            pwd
            echo "directory contents:"
            /bin/ls -la
            npm ci
            npm run build
            
            # Move build output to dist directory
            mkdir -p "../../dist/$ID"
            mv dist/* "../../dist/$ID/"
            
            # Return to root
            cd ../../
          done

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
